# Generated by Django 4.2.7 on 2024-01-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagePromotion',
            field=models.ImageField(blank=True, upload_to='products-promotion-img'),
        ),
    ]
