# Generated by Django 4.2.7 on 2024-01-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_imagepromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products_app.product')),
                ('imagePromotion', models.ImageField(blank=True, upload_to='products-promotion-img')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagePromotion',
        ),
    ]
