# Generated by Django 4.2.7 on 2024-01-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_productpromotion_remove_product_imagepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromotion',
            name='namePromotion',
            field=models.CharField(default='YourDefaultValueHere', max_length=50),
        ),
    ]
