# Generated by Django 4.2.7 on 2024-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_productpromotion_namepromotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPromotion',
        ),
    ]
